package presentacion;

import java.awt.Color;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import logic.createFlight;
import logic.Validations;

/**
 *
 * @author Admin
 */
public class FlightCreator extends javax.swing.JDialog {

    createFlight createflight = new createFlight();
    Validations validationS = new Validations();

    private int idFlight;

    public static String rutaImagenAvion = "src/resources/photos/avion3.jpg";

    public FlightCreator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadImages();
        createflight.fillComboBoxes(jcbAeropuertoSalida, jcbAeropuertoLlegada, jcbAerolinea);
        validationS.configurateSpinner(jSpinner1);
        validationS.configurateSpinner(jSpinner2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFechaSalida = new javax.swing.JLabel();
        lblAerolinea = new javax.swing.JLabel();
        lblAeropuertoSalida = new javax.swing.JLabel();
        lblFechaLlegada = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        lblAeropuertoLlegada = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCreacionVuelos = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        jcbAerolinea = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        jcbAeropuertoSalida = new javax.swing.JComboBox<>();
        jcbAeropuertoLlegada = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        dCCFechaSalida = new datechooser.beans.DateChooserCombo();
        dCCFechaEntrada = new datechooser.beans.DateChooserCombo();
        lblImagenExit = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechaSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaSalida.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaSalida.setText("FECHA DE SALIDA");
        jPanel1.add(lblFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        lblAerolinea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAerolinea.setForeground(new java.awt.Color(255, 255, 255));
        lblAerolinea.setText("AEROLINEA");
        jPanel1.add(lblAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        lblAeropuertoSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAeropuertoSalida.setForeground(new java.awt.Color(255, 255, 255));
        lblAeropuertoSalida.setText("AEROPUERTO DE SALIDA");
        jPanel1.add(lblAeropuertoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        lblFechaLlegada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaLlegada.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaLlegada.setText("FECHA DE LLEGADA");
        jPanel1.add(lblFechaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        lblHoraSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHoraSalida.setForeground(new java.awt.Color(255, 255, 255));
        lblHoraSalida.setText("HORA DE SALIDA");
        jPanel1.add(lblHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        lblAeropuertoLlegada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAeropuertoLlegada.setForeground(new java.awt.Color(255, 255, 255));
        lblAeropuertoLlegada.setText("AEROPUERTO DE LLEGADA");
        jPanel1.add(lblAeropuertoLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("PRECIO");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORA DE LLEGADA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        lblCreacionVuelos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCreacionVuelos.setForeground(new java.awt.Color(255, 255, 255));
        lblCreacionVuelos.setText("CREACION DE VUELOS");
        jPanel1.add(lblCreacionVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnCrear.setBackground(new java.awt.Color(60, 63, 65));
        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jcbAerolinea.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcbAerolinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una aerolinea" }));
        jPanel1.add(jcbAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 30));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(204, 204, 204));
        txtPrecio.setText("Ingrese un precio");
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioMousePressed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 120, 30));

        jcbAeropuertoSalida.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcbAeropuertoSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un aeropuerto de salida" }));
        jPanel1.add(jcbAeropuertoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 300, 30));

        jcbAeropuertoLlegada.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jcbAeropuertoLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un aeropuerto de llegada" }));
        jPanel1.add(jcbAeropuertoLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 300, 30));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 150, 30));

        jSpinner2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 150, 30));
        jPanel1.add(dCCFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, 30));
        jPanel1.add(dCCFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 150, 30));

        lblImagenExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenExitMouseClicked(evt);
            }
        });
        jPanel1.add(lblImagenExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Validations validationS = new Validations();
    createFlight createFlight = new createFlight();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat timeFormat = new SimpleDateFormat("h:mm a");
    int flightId = createFlight.generateUniqueFlightId();

    String airlineName = (String) jcbAerolinea.getSelectedItem();
    String departureAirport = (String) jcbAeropuertoSalida.getSelectedItem();
    String arrivalAirport = (String) jcbAeropuertoLlegada.getSelectedItem();
    Date arrivalHour = (Date) jSpinner2.getValue();
    Date departureDate = (Date) dCCFechaSalida.getSelectedDate().getTime();
    Date departureHour = (Date) jSpinner1.getValue();
    Date arrivalDate = (Date) dCCFechaEntrada.getSelectedDate().getTime();
    String priceText = txtPrecio.getText();

    int price = 0;
    try {
        price = Integer.parseInt(priceText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El precio ingresado no es un número válido:");
        return; // Detener la ejecución si el precio no es válido
    }

    if (!validationS.validateNotLeaveBlankSpace(airlineName, "Seleccione una aerolinea")) {
        return; // Detener la ejecución si la aerolínea no es válida
    }

    if (!validationS.validateAirport(departureAirport, arrivalAirport)) {
        return; // Detener la ejecución si los aeropuertos no son válidos
    }

    if (!validationS.validateArrivalDate(departureDate, arrivalDate)) {
        return; // Detener la ejecución si la fecha de llegada no es válida
    }

    if (!validationS.validateArrivalTime(departureDate, departureHour, arrivalDate, arrivalHour)) {
        return; // Detener la ejecución si la hora de llegada no es válida
    }

    int planeId = createFlight.getPlaneId(airlineName);
    int[] tripulacion = createFlight.getCrew(airlineName);

    if (planeId == 0) {
        JOptionPane.showMessageDialog(this, "No hay aviones disponibles en la aerolínea seleccionada", "Información", JOptionPane.INFORMATION_MESSAGE);
        return; // Detener la ejecución si no hay aviones disponibles
    }

    if (tripulacion[0] == 0 || tripulacion[1] == 0) {
        JOptionPane.showMessageDialog(this, "Personal disponible insuficiente", "Información", JOptionPane.INFORMATION_MESSAGE);
        return; // Detener la ejecución si no hay personal suficiente
    }

    int airlineId = createFlight.getAirlineIdByName(airlineName);
    int departureAirportId = createFlight.getAirportIdByName(departureAirport);
    int arrivalAirportId = createFlight.getAirportIdByName(arrivalAirport);
    int duration = createFlight.getDuration(departureDate, departureHour, arrivalDate, arrivalHour);

    String[] flight = new String[13];
    flight[0] = String.valueOf(flightId);
    flight[1] = String.valueOf(airlineId);
    flight[2] = String.valueOf(price);
    flight[3] = dateFormat.format(departureDate);
    flight[4] = timeFormat.format(departureHour);
    flight[5] = String.valueOf(departureAirportId);
    flight[6] = dateFormat.format(arrivalDate);
    flight[7] = timeFormat.format(arrivalHour);
    flight[8] = String.valueOf(arrivalAirportId);
    flight[9] = String.valueOf(duration);
    flight[10] = String.valueOf(planeId); 
    flight[11] = String.valueOf(tripulacion[0]); 
    flight[12] = String.valueOf(tripulacion[1]); 

    createFlight.addFlight(flight);
    JOptionPane.showMessageDialog(this, "Vuelo añadido", "Información", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMousePressed
        if (txtPrecio.getText().equals("Ingrese un precio")) {
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPrecioMousePressed

    private void lblImagenExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenExitMouseClicked
        Window window = SwingUtilities.getWindowAncestor(lblImagenExit);
        window.dispose();
    }//GEN-LAST:event_lblImagenExitMouseClicked

    private void loadImages() {
        Validations validations = new Validations();
        validations.loadExitImage(lblImagenExit);
        validations.cargarImagen(lblImagen, rutaImagenAvion);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlightCreator dialog = new FlightCreator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private datechooser.beans.DateChooserCombo dCCFechaEntrada;
    private datechooser.beans.DateChooserCombo dCCFechaSalida;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JComboBox<String> jcbAerolinea;
    private javax.swing.JComboBox<String> jcbAeropuertoLlegada;
    private javax.swing.JComboBox<String> jcbAeropuertoSalida;
    private javax.swing.JLabel lblAerolinea;
    private javax.swing.JLabel lblAeropuertoLlegada;
    private javax.swing.JLabel lblAeropuertoSalida;
    private javax.swing.JLabel lblCreacionVuelos;
    private javax.swing.JLabel lblFechaLlegada;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenExit;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
